baseURL = "https://biogroundz.com/"
languageCode = "en-us"
title = "Biogroundz Verticals"
theme = ""
enableGitInfo = true
enableRobotsTXT = true
paginate = 10
canonifyURLs = false

[params]
  brandName = "Biogroundz"
  plausibleDomain = "biogroundz.com" # or leave blank if not using Plausible

[minify]
  minifyOutput = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
