languageCode = "en-us"
title = "Biogroundz Verticals"
theme = ""
enableGitInfo = true
enableRobotsTXT = true
paginate = 10


baseURL = "https://taguniversal.github.io/biogz/"
relativeURLs = true
canonifyURLs = true

[params]
  brandName = "Biogroundz"
  plausibleDomain = "biogroundz.com" # or leave blank if not using Plausible

[minify]
  minifyOutput = true

[build]
  writeStats = true
  
[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.postCSS]
    use = ["postcss"]

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
